### ISSUE TITLE
Image breaking if image size in file name

### ISSUE THREAD

**Issue by marcavila** [Mecanik/cloudflare-image-resizing#8] opened 2022-02-22 08:53 UTC
Hello, 

Just an FYI, it seems if an image has the image size in the image file name (i.e. UI-paths-800x800-1.jpg), the plugin strips out part of the image file name (i.e. UI-paths.1.jpg), which causes a 404.

**Comment by Mecanik** [comment] 2022-02-22 09:18
Indeed, this is a bug in the current regex when stripping out the image size. 

The idea of that feature added by other contributors was to tell Cloudflare to resize the original image and not one already resized.

For the past week I have been working on a full rewrite of the plugin and will publish today/tomorrow which fixes this problem.

Stay tuned :)

**Comment by Mecanik** [comment] 2022-03-04 18:13
Hello, please download the latest plugin and see the fix :)

**Comment by mbgulden** [comment] 2022-05-19 16:49
Hey, nice job on the plugin! I'm having a similar problem with the 404 errors on images. The image size isn't being stripped, so that initial issue is fixed for sure, but when there's a number at the end of the image file name, the image breaks (at least in my case), and I'm left with a 1:2 ratio gradient image placeholder. Is anyone else seeing that?

**Comment by mbgulden** [comment] 2022-05-19 19:02
Awesome! Thanks for being so quick with possible solutions. I'm going to try it out now on local.

**Comment by mbgulden** [comment] 2022-05-19 23:46
**Solution 1:** Didn't work, but is close. I feel like the regex just needs to be tweaked.
It seems like the height value was getting limited to 2 characters. I played around with the regex, but didn't get the results I was looking for.

This is off topic, but setting width and height via query string like imgix seems like an interesting option
![image](https://user-images.githubusercontent.com/9388838/169420449-ff0c81ff-31c9-4d9d-a406-d2985712024a.png)

Replaced the solution 1 regex and got this output:
```<img src="https://activeoahutours.com/cdn-cgi/image/width=650,height=32,fit=crop,quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2022/04/Kaneohe-bay-kayaking-kualoa-mountains-views-mokolii650x325.jpg" alt="Kaneohe Bay Kayaking, Kualoa Mountain and Mokolii views">```

```<img width="1993" height="797" src="https://activeoahutours.com/cdn-cgi/image/quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5291_2000_2000_1x2.5.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="Tandem Kayak Rentals on Oahu, Free Delivery" loading="lazy" srcset="https://activeoahutours.com/cdn-cgi/image/quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5291_2000_2000_1x2.5.jpg 1993w, https://activeoahutours.com/cdn-cgi/image/width=650,height=26,fit=crop,quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5291_2000_2000_1x2.5.jpg 650w, https://activeoahutours.com/cdn-cgi/image/width=768,height=30,fit=crop,quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5291_2000_2000_1x2.5.jpg 768w, https://activeoahutours.com/cdn-cgi/image/width=1024,height=40,fit=crop,quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5291_2000_2000_1x2.5.jpg 1024w, https://activeoahutours.com/cdn-cgi/image/width=480,height=19,fit=crop,quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5291_2000_2000_1x2.5.jpg 480w" sizes="(max-width: 1993px) 100vw, 1993px">
```

```
<a href="https://activeoahutours.com/cdn-cgi/image/quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5287_2000.jpg">
<img src="https://activeoahutours.com/cdn-cgi/image/width=115,height=11,fit=crop,quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5287_2000.jpg" alt="Easy carry handle, Oahu Ocean Kayak Rentals" height="115" width="115">
</a>
```

**Solution 2:** That just seems to bypass the image sizing:

<img width="1993" height="797" src="https://activeoahutours.com/cdn-cgi/image/quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5291_2000_2000_1x2.5.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="Tandem Kayak Rentals on Oahu, Free Delivery" loading="lazy" srcset="https://activeoahutours.com/cdn-cgi/image/quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5291_2000_2000_1x2.5.jpg 1993w, https://activeoahutours.com/cdn-cgi/image/quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5291_2000_2000_1x2.5-650x260.jpg 650w, https://activeoahutours.com/cdn-cgi/image/quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5291_2000_2000_1x2.5-768x307.jpg 768w, https://activeoahutours.com/cdn-cgi/image/quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5291_2000_2000_1x2.5-1024x409.jpg 1024w, https://activeoahutours.com/cdn-cgi/image/quality=80,format=auto,onerror=redirect,metadata=none/wp-content/uploads/2018/11/DSC5291_2000_2000_1x2.5-480x192.jpg 480w" sizes="(max-width: 1993px) 100vw, 1993px">

Since it did not go well, I skipped on all the Image Resizing steps. The plugin still converts the images and all that great.

Also, I'm pretty sure this is the answer, but this image isn't being converted because it's a relative image, right? 
It just needs to be an absolute link?
<img src="/wp-content/uploads/2018/11/DSC5268_2000-650x433.jpg" alt="Oahu Stand Up Paddle Board Rentals">

Thanks for your help!

**Comment by Mecanik** [comment] 2022-05-20 03:18
Thanks, I will be honest that regex is really stressing me out. As for solution 2, it works as intended but some images will not get resized because they come from widgets... and there is no widget hook yet. 

That is the reason why I`m releasing a Worker based solution soon that will fix all this and have 100% all images rewritten.

**Comment by gardar** [comment] 2022-09-21 10:56
Doesn't wordpress always apply the size to the end of the filename? How about a regex that simply matches that?

Something like:
```php
(([0-9]{1,4})x([0-9]{1,4})){1}(?=\.\S*$)
```

We can even simplify it like this:
```php
((\d+)x(\d+))(?=\.\S+$)
```

**Comment by Mecanik** [comment] 2023-01-31 18:39
Hello, I am closing this issue since I have finally finished the Cloudflare Worker alternative. It's much more advanced and does not have this issue.

Please read my article on how to use and get the code: https://mecanik.dev/en/posts/cloudflare-image-resizing-for-wordpress/

**Closed by Mecanik** 2023-01-31 18:39 UTC
Labels: help wanted
